pub mod audio;
pub mod cpu;
pub mod gamescope;
pub mod gpu_amd;
pub mod mangohud;
pub mod memory;
pub mod network;
pub mod power;
pub mod storage;
pub mod stream_client;

pub use audio::AudioCollector;
pub use cpu::CpuCollector;
pub use gamescope::FrameCollector;
pub use gpu_amd::GpuAmdCollector as GpuCollector;
pub use memory::MemoryCollector;
pub use network::NetworkCollector;
pub use power::PowerCollector;
pub use storage::StorageCollector;
pub use stream_client::StreamClientCollector;
